export const state = {
    pdfDoc: null,
    pdfBytes: null,
    currentFilename: '',
    currentScale: 1,
    pageRotation: 0,
    headerMode: 'minimal',
    annotationActive: false,
    eraserActive: false,
    freehandActive: false,
    currentAnnotationMode: 'highlight',
    currentAnnotationColor: '#ffeb3b',
    currentAnnotationSize: 4,
    drawings: {},
    focusMode: 0,
    focusSize: 150,
    renderTasks: {},
    renderingStates: {},
    textLayerTasks: {},
    annotationLoadVersions: {},
    pendingAnnotationRemovals: new Map(),
};